FROM centos:7

#Configuration du proxy
#ENV http_proxy http://usr:pwd@192.168.77.12:8080
#ENV https_proxy http://usr:pwd@192.168.77.12:8080


#Configuration des variables d'environnement
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre

#Exposition de port
EXPOSE 22
EXPOSE 80


#Used root
USER root
#definition d'un mot de passe
RUN echo 'root:rooting' | chpasswd

#Install update
RUN yum -y update && yum clean all


#Installation package centos
RUN yum -y install \
        java-1.8.0-openjdk \
        java-1.8.0-openjdk-devel \
        openssh \
        openssh-server \
        openssh-clients \
        net-tools \
        && yum clean all

#Configuration de la partie SSH
RUN echo 'Y' | ssh-keygen -b 4096 -t rsa -N '' -f /root/.ssh/id_rsa
COPY --chown=root config/ssh/id_rsa.pub /root/.ssh/authorized_keys

#configuration du serveur SSH
RUN echo "PubkeyAuthentication yes" >> /etc/ssh/ssh_config
RUN echo "Host *" >> /etc/ssh/ssh_config

#configuration du serveur SSH
#RUN sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's@HostKey /etc/ssh/ssh_host_dsa_key@#HostKey /etc/ssh/ssh_host_dsa_key@' /etc/ssh/sshd_config
RUN sed -i 's@HostKey /etc/ssh/ssh_host_ecdsa_key@#HostKey /etc/ssh/ssh_host_ecdsa_key@' /etc/ssh/sshd_config
RUN sed -i 's@HostKey /etc/ssh/ssh_host_ed25519_key@#HostKey /etc/ssh/ssh_host_ed25519_key@' /etc/ssh/sshd_config
RUN sed -i 's@PasswordAuthentication yes@PasswordAuthentication no@' /etc/ssh/sshd_config

RUN cp /root/.ssh/id_rsa.pub /etc/ssh/ssh_host_rsa_key.pub
RUN cp /root/.ssh/id_rsa /etc/ssh/ssh_host_rsa_key


#Execution du service SSH 
CMD ["/usr/sbin/sshd", "-D"]
